#!/usr/bin/env ruby

require 'ipaddr'

amazon_ranges = File.read('amazon-ranges').split(/\n/).select{|l| l.length > 0 }.map{ |l| IPAddr.new(l) }
gce_ranges = File.read('gce-ranges').split(/\n/).select{|l| l.length > 0 }.map{ |l| IPAddr.new(l) }

def find_in_ranges(ipaddr, ranges)
	ranges.each do |range|
		return true if range.include?(ipaddr)
	end
	false
end

$stdin.readlines.each do |ip|
	ip.chomp!
	ipaddr = IPAddr.new(ip)
	if find_in_ranges(ipaddr, amazon_ranges)
		puts 'amazon,' + ip
	elsif find_in_ranges(ipaddr, gce_ranges)
		puts 'gce,' + ip
	else
		puts 'unknown,' + ip
	end
end
