#!/usr/bin/env bash

set +x

ips=$(s3cmd get -r s3://lattice-logs/logs/ - | sed -E '/^s3:\/\//d;/^ [[:digit:]]+ of [[:digit:]]+/d;/^.*user\/lattice-concourse/d;s/^.* (([[:digit:]]+\.){3}[[:digit:]]+) .*$/\1/g')
